---
resources:
  - name: super-app
    type: git
    branch: dev
    source:
      uri: https://github.com/ahelal/concourse-tutorial.git

jobs:
  - name: Test
    plan:
    - get: super-app
      trigger: true
    - task: Testing
      config:
        platform: linux
        image_resource:
          type: docker-image
          source: {repository: ubuntu}
        run:
          path: ls
          args: ["-l"]

        inputs:
          - name: super-app
