---
resources:
  - name: super-app
    type: git
    source:
      uri: https://github.com/hellofresh/concourse-tutorial.git
      branch: ci

jobs:
  - name: Master unit testing
    plan:
    - get: super-app
      trigger: true

    - task: run unit
      file: super-app/tutorial/scenario.2/4-deconstructing/tasks/unit.yml

  - name: Master lint testing
    plan:
    - get: super-app
      trigger: true

    - task: run lint
      file: super-app/tutorial/scenario.4/1-multi-os/tasks/lint.yml

  - name: Master building linux
    plan:
    - get: super-app
      passed: ["Master unit testing", "Master lint testing"]
      trigger: true

    - task: build
      file: super-app/tutorial/scenario.4/1-multi-os/tasks/build_linux.yml

  - name: Master building Mac
    plan:
    - get: super-app
      passed: ["Master unit testing", "Master lint testing"]
      trigger: true

    - task: build
      file: super-app/tutorial/scenario.4/1-multi-os/tasks/build_mac.yml



    # - task: integeration test
    #   file: super-app/tutorial/scenario.2/1-multi-os/tasks/integeration.yml
