---

platform: linux
image_resource:
  type: docker-image
  source: {repository: golang}
run:
  path: sh
  args:
  - -exc
  - |
    ./scripts/go_deps.sh
    ./scripts/go_build.sh darwin $(cat ../semantic/version)
    mv super_*_linux_amd64 ../artifact_mac
  dir: super-app/
inputs:
  - name: super-app
outputs:
  - name: artifact_mac
  - name: semantic