---
resources:
  - name: super-app
    type: git
    source:
      uri: https://github.com/hellofresh/concourse-tutorial.git
      branch: ci

jobs:
  - name: Master unit testing
    plan:
    - get: super-app
      trigger: true

    - task: run unit
      file: super-app/tutorial/scenario.3/1-pr/tasks/unit.yml

  - name: Master lint testing
    plan:
    - get: super-app
      trigger: true

    - task: run lint
      file: super-app/tutorial/scenario.3/1-pr/tasks/lint.yml

  - name: Master building & integeration testing
    plan:
    - get: super-app
      passed: ["unit testing", "lint testing"]
      trigger: true

    - task: build
      file: super-app/tutorial/scenario.3/1-pr/tasks/build.yml

    - task: integeration test
      file: super-app/tutorial/scenario.3/1-pr/tasks/integeration.yml
